Fix bad serial data causing exceptions (#172)
It seems that sometimes a single byte comes over the wire and we hit an exception

Uncaught (in promise) TypeError: r.next is not a function
at Function.lo.TextAttributes.splitWidecharString (app.js:12)
at lo.Terminal.print (app.js:12)
at r (app.js:12)
at lo.VT.parseUnknown_ (app.js:12)
at lo.VT.interpret (app.js:12)
at lo.Terminal.interpret (app.js:12)
at lo.Terminal.IO.print.lo.Terminal.IO.writeUTF16 (app.js:12)
at hdctools-console-view.js:80
at N.readloop (lib.js:32)

It looks like we're trying to parse the data coming over the wire and we think
it's a UTF16 codepoint but it's just junk/noise. This usually happens
when we reboot the board. Add a try catch for now so the whole app doesn't
crash.

Signed-off-by: Stephen Boyd swboyd@chromium.org